#!/bin/bash
set -e

usage() {
	echo "git pr rev-list [<remote>]"
	exit $1
}

remote=""
pr=""
declare -a list
while [ $# -ge 1 ]; do
	case $1 in
	--help|-h|--usage|-\?)
		usage 0
		;;
	--remote=*)
		remote=${1#--remote=} && shift
		continue
		;;
	--remote)
		[ $# -ge 2 ] && remote=$2 && shift 2
		continue
		;;
	--pr=*)
		pr=${1#--pr=} && shift
		continue
		;;
	--pr)
		[ $# -ge 2 ] && pr=$2 && shift 2
		continue
		;;
	*)
		list[${#list[*]}]=$1
		;;
	esac
	shift
done
eval set -- "${list[$@]}"

if [ -z $pr ]; then
	pr=${1} && shift
fi
pr=${pr#pr/}
upstream_name=$(git config --get vathpela.toys.upstream) || upstream_name=upstream
if [ -z $remote ]; then
	remote=${1:-${upstream_name}}
	shift >/dev/null 2>&1 || :
fi

merge=""
if [ -f ".git/refs/remotes/${remote}/pr-merge/${pr}" ]; then
	merge="refs/remotes/${remote}/pr-merge/${pr}^"
fi
eval git rev-list $(git rev-parse --sq --revs-only --no-flags --default HEAD "${merge}..refs/remotes/${remote}/pr/${pr}")
