#!/bin/bash
set -e
usage() {
	echo "git show-pull <remote> <pull_number>"
	exit $0
}

for x in "$@" ; do
	case "$x" in
	--help|-h|--usage|-\?)
		usage 0
		;;
	esac
done

if [ $# -ne 2 ]; then
	usage 1 1>&2
fi

exec git cherry-pick "..refs/pull/$1/$2"
