#!/bin/bash -e
set -e

usage() {
	echo "git pr fetch <pr_number> [<remote>]"
	exit $1
}

remote=""
pr=""
declare -a list
while [ $# -ge 1 ]; do
	case $1 in
	--help|-h|--usage|-\?)
		usage 0
		;;
	--remote=*)
		remote=${1#--remote=} && shift
		continue
		;;
	--remote)
		[ $# -ge 2 ] && remote=$2 && shift 2
		continue
		;;
	--pr=*)
		pr=${1#--pr=} && shift
		continue
		;;
	--pr)
		[ $# -ge 2 ] && pr=$2 && shift 2
		continue
		;;
	*)
		list[${#list[*]}]=$1
		;;
	esac
	shift
done
eval set -- "${list[$@]}"

if [ -z $pr ]; then
	pr=${1} && shift
fi
pr=${pr#pr/}
if [ -z $remote ]; then
	remote=${1:-upstream}
	shift >/dev/null 2>&1 || :
fi

[ $# -ge 1 ] && shift || :

git fetch -fu "${remote}" "refs/pull/${pr/}/head:refs/remotes/${remote}/pr/${pr}"
git pr log "${pr}" "${remote}" "$@"
